---
title: "Regression"
author: "Frank"
date: "11/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(zipcode)
library(tidyverse)
library(usmap)
library(ggplot2)
library(tidytext)
library(tm)
library(topicmodels)
library(wordcloud)
library(RColorBrewer)
library(sentimentr)
library(lme4)
library(arm)
library(pROC)
```


```{r}
# Reading samples
sample <- read.csv("Real_Talk_Data.csv", stringsAsFactors = FALSE)
sample <- sample[1:812,]
colnames(sample)[13] <- "zip"
sample$zip[sample$zip < 10000 & is.na(sample$zip) == F] <- 
  sprintf("%05d", sample$zip[sample$zip < 10000 & is.na(sample$zip) == F])
sample <- sample[ , colSums(!is.na(sample)) != 0]
sample$Story <- do.call(paste, c(sample[18:127], sep=" "))
sample <- sample[,c(1:17,128)]

# Category Data Cleaning up
sample$LGBTQ.[sample$LGBTQ. == "" | is.na(sample$LGBTQ.) == T] <- "Prefer not to share"
sample$LGBTQ.[sample$LGBTQ. == "nyes" | sample$LGBTQ. == "yes "] <- "yes"
sample$LGBTQ.[sample$LGBTQ. == "on"] <- "no"
sample$Gender[sample$Gender == "" | is.na(sample$Gender) == T] <- "Prefer not to share"
sample$Gender[sample$Gender == "abstain" | sample$Gender == "abstain "] <- "Prefer not to share"
sample$Gender[sample$Gender == "Female"] <- "female"
sample$Gender[sample$Gender == "Male" | sample$Gender == "male "] <- "male"
sample$Gender[sample$Gender == "Other" | sample$Gender == "non-binary" | sample$Gender == "Non-binary"] <- "other"
sample$Submission..Type[sample$Submission..Type == "squarespace"] <- "Mobile App"
sample$Submission..Type[sample$Submission..Type == "online"] <- "Website"
sample$Submission..Type[sample$Submission..Type == "peers"] <- "in person"

# Adding Sentiment score
sample$sentiment <- sentiment_by(sample$Story)[,4]
sample$sentiment <- 10*apply(sample$sentiment,2,as.numeric)

# Adding zipcode, states, count, and other predictors
data(zipcode)
zip <- zipcode %>% 
  dplyr::select(zip, state) %>% 
  distinct(zip, .keep_all = TRUE)
samplestate <- merge(sample, zip, by = "zip")
samplecount <- samplestate %>% 
  group_by(state) %>% 
  count(state)
realtalk <- merge(sample, zip, by = "zip", all.x = TRUE)
regdata <- realtalk[c(-3,-10,-11,-17,-131,-133,-272,-411,-449,-614,-622,-769,-777,-806), c(1,19,4,10:12,17:18,20)]
sentimentmean <- regdata %>% 
  group_by(state) %>% 
  summarise(mean_sent = mean(sentiment, na.rm = T))
sentimentmean <- merge(sentimentmean, samplecount, by = "state")
sentimentmean$red <- 0
sentimentmean$red[c(1:3,5,7,8,10,11,13:16,19:28,33,34,36,38:42,44:46)] <- 1
```

```{r}
# Preprocessing regression data
if (!"red" %in% colnames(regdata)){
  regdata <- merge(regdata, sentimentmean[,c(1,4)], by = "state", all.x = TRUE)
}
regdata$Gender <- as.factor(regdata$Gender)
regdata$LGBTQ. <- as.factor(regdata$LGBTQ.)
regdata$state <- as.factor(regdata$state)
regdata$Submission..Type <- as.factor(regdata$Submission..Type)
regdata$Subject <- as.factor(regdata$Subject)
regdata$wordcount <- str_count(regdata$Story, '\\w+')
regdata$sentiment2 <- 0
regdata$sentiment2[regdata$sentiment > 0] <- 1

# Creating Regions
regdata$Reg[regdata$state %in% c("WA", "OR", "CA", "NV", "ID", "MT", "WY", "UT", "CO", "AK", "HI")] <- "west"
regdata$Reg[regdata$state %in% c("ND", "MN", "WI", "MI", "OH", "IN", "IL", "IA", "MO", "SD", "NE", "KS")] <- "midwest"
regdata$Reg[regdata$state %in% c("AZ", "NM", "OK", "TX")] <- "southwest"
regdata$Reg[regdata$state %in% c("AR", "LA", "MS", "AL", "GA", "FL", "SC", "NC", "KY", "TN", "WV", "VA", "MD", "DE")] <- "southeast"
regdata$Reg[regdata$state %in% c("ME", "VT", "NH", "MA", "NY", "RI", "CT", "NJ", "PA")] <- "northeast"

# Regdata2 is the datasets with no NA rows
regdata2 <- regdata[is.na(regdata$state) == F & is.na(regdata$Age) == F,]
```

```{r}
# Basic population visualization
plot_usmap(regions = "states", data = samplecount, values = "n", lines = "grey") + 
  scale_fill_continuous(low = "#FFCC33", high = "brown", name = "Story Population", label = scales::comma) +
  labs(title = "Real Talk Sample Density in US") + 
  theme(panel.background = element_rect(colour = "black", fill = "white"), legend.position = "right")
plot_usmap(regions = "states", data = sentimentmean, values = "mean_sent", lines = "grey") + 
  scale_fill_continuous(low = "red", high = "white", name = "Sentiment_Score", label = scales::comma) +
  labs(title = "Real Talk Sample Sentiment in US") + 
  theme(panel.background = element_rect(colour = "black", fill = "white"), legend.position = "right")
```

```{r, fig.height= 15, fig.width= 7}
# EDA
par(mfrow = c(5,2))
hist(regdata$sentiment, breaks =20, main = "Histogram of sentiment score distribution")
plot(sentiment~Age, data = regdata, main = "sentiment ~ age")
plot(sentiment~Gender, data = regdata, main = "sentiment ~ gender")
plot(sentiment~LGBTQ., data = regdata, main = "sentiment ~ LGBT status")
plot(sentiment~Subject, data = regdata, main = "sentiment ~ different subjects")
plot(sentiment~Submission..Type, data = regdata, main = "sentiment ~ different submission types")
plot(sentiment~wordcount, data = regdata, main = "sentiment ~ word count of the story submitted")
boxplot(wordcount~sentiment2, data = regdata2, main = "categorical sentiment score ~ word count",
        xlab = "0 : sentimentscore <= 0,   1 : sentimentscore > 0", ylab = "wordcount")
boxplot(sentiment~Reg, data = regdata2, main = "sentiment ~ different region")
```

```{r}
reg1 <- glm(sentiment2 ~ Age + Gender + LGBTQ. + Subject + Submission..Type + wordcount + red + Reg, family = binomial, data = regdata2)
summary(reg1)
roc(regdata2$sentiment2, fitted(reg1), plot=T, legacy.axes=T)
binnedplot(x=regdata2$Age, y = regdata2$sentiment2 - fitted(reg1), xlab = "Age", ylab = "Residuals", main = "Binned residuals versus Age")
```



